spring :
  datasource:
    url: jdbc:mysql://localhost:10086/shiro?characterEncoding=utf-8
    username: root
    password: root
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
  #  dangodb:
  #    uri: mongodb://localhost:27017/testta:
  #    mo
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
    template-loader-path: classpath:/static/
    suffix: .html
  aop:
    auto: true
server:
  port: 8081
  servlet:
    context-path: /
mybatis-plus:
  type-aliases-package: com.ji.domain
  mapper-locations: classpath:mapper/*.xml